Repository linktimecloud/kubernetes-data-platform, pull requests merged in 2024-04, with the labels that each got.

#21 Fix: repo clone permission
  pkg/utils/utils.go
Labels: bug

#23 Fix: Correct and add some details in the tutorials
  docs/en/user-tutorials/import-from-mysql-to-hive.md
  docs/en/user-tutorials/import-from-mysql-to-kafka.md
  docs/zh/user-tutorials/import-from-mysql-to-hive.md
  docs/zh/user-tutorials/import-from-mysql-to-kafka.md
Labels: documentation

#22 Docs: add KDP overview
  README.md
  README_zh.md
  docs/en/getting-started/overview.md
  docs/zh/getting-started/overview.md
Labels: documentation

#25 Docs: add developer-guide docs
  README.md
  README_zh.md
  docs/en/catalog-overview/catalogs.md
  docs/en/developer-guide/developer-guide.md
  docs/en/user-tutorials/import-from-rbdms-to-hive.md
  docs/en/user-tutorials/import-from-rdbms-to-kafka.md
  docs/en/user-tutorials/tutorials.md
  docs/zh/catalog-overview/catalogs.md
  docs/zh/developer-guide/developer-guide.md
  docs/zh/user-tutorials/import-from-rdbms-to-hive.md
  docs/zh/user-tutorials/import-from-rdbms-to-kafka.md
  docs/zh/user-tutorials/tutorials.md
Labels: documentation

#34 Docs: Correct the position of "Flink on Hive" in the document
  docs/en/user-tutorials/import-from-rbdms-to-hive.md
  docs/zh/user-tutorials/import-from-rdbms-to-hive.md
Labels: documentation

#38 Fix: oam-operator registry url incorrect
  infra/kdp-core/resources/kdp-oam-operator.cue
Labels: bug

#41 Docs: Fix flink typo
  catalog/flink/apps/streampark.app/README.md
  catalog/flink/apps/streampark.app/i18n/en/README.md
  docs/en/catalog-overview/Flink/developer-guide.md
  docs/zh/catalog-overview/Flink/developer-guide.md
  docs/zh/user-tutorials/import-from-rdbms-to-hive.md
Labels: documentation

#45 Fix: fix relative links in tutorials
  docs/en/user-tutorials/import-from-rdbms-to-kafka.md
  docs/zh/user-tutorials/import-from-rdbms-to-kafka.md
Labels: documentation

#47 Refactor: remove zk/hive/spark raw type
  catalog/hive/x-definitions/app-hive-metastore.cue
  catalog/hive/x-definitions/app-hive-server2.cue
  catalog/spark/x-definitions/app-spark-history-server.cue
  catalog/zookeeper/x-definitions/app-zookeeper.cue
Labels: enhancement

#46 Fix: cherrypick/fix relative links in tutorials
  docs/en/user-tutorials/import-from-rdbms-to-kafka.md
  docs/zh/user-tutorials/import-from-rdbms-to-kafka.md
Labels: documentation

#50 Fix: cherry pick #47 remove zk/hive/spark raw type
  catalog/hive/x-definitions/app-hive-metastore.cue
  catalog/hive/x-definitions/app-hive-server2.cue
  catalog/spark/x-definitions/app-spark-history-server.cue
  catalog/zookeeper/x-definitions/app-zookeeper.cue
Labels: cherry pick

#51 Fix: cherry pick #48 remove hdfs deprecated proxyuser
  catalog/hdfs/apps/hdfs.app/app.yaml
  catalog/hdfs/x-definitions/app-hdfs.cue
Labels: cherry pick

#53 Fix: improved installation stability on poor disk I/O performance environment
  infra/openebs/template.cue
  pkg/vela/vela.go
Labels: enhancement

#55 Fix: cherry pick #54 add missing k8s resources for hue and streampark
  catalog/flink/x-definitions/app-streampark.cue
  catalog/hdfs/x-definitions/app-httpfs.cue
  catalog/hue/x-definitions/app-hue.cue
Labels: cherry pick

#57 Refactor: improved hms-admin-cfg string format (#56)
  catalog/hive/x-definitions/app-hive-metastore.cue
Labels: cherry pick

#59 Fix: removed problematic parameter when install vela
  pkg/vela/vela.go
Labels: bug
