Repository linktimecloud/kubernetes-data-platform, pull requests merged in 2024-05, with the labels that each got.

#63 Fix: tuning infra MySQL startupProbe failureThreshold on poor I/O env
  infra/mysql/resources/mysql.cue
Labels: bug

#70 Feat: integration with mainstream K8s distributions
  infra/kdp-core/resources/kdp-catalog-manager.cue
  infra/kdp-core/resources/kdp-ux.cue
  infra/kdp-core/resources/shared-configs.cue
  infra/kdp-core/template.cue
  infra/openebs/parameter.cue
  infra/openebs/template.cue
  infra/plg-stack/parameter.cue
  infra/plg-stack/resources/prometheus.cue
Labels: enhancement

#64 Feat: add clickhouse
  catalog/clickhouse/README.md
  catalog/clickhouse/apps/clickhouse.app/README.md
  catalog/clickhouse/apps/clickhouse.app/app.yaml
  catalog/clickhouse/apps/clickhouse.app/i18n/en/README.md
  catalog/clickhouse/apps/clickhouse.app/metadata.yaml
  catalog/clickhouse/i18n/en/README.md
  catalog/clickhouse/metadata.yaml
  catalog/clickhouse/x-definitions/app-clickhouse.cue
  catalog/clickhouse/x-definitions/setting-clickhouse.cue
Labels: enhancement

#75 Feat: add ingress for clickhouse
  catalog/clickhouse/x-definitions/app-clickhouse.cue
Labels: enhancement

#74 Feat: add hdfs to hdfs tutorial
  docs/en/user-tutorials/import-from-hdfs-to-hdfs.md
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/import-from-hdfs-to-hdfs.md
  docs/zh/user-tutorials/tutorials.md
Labels: documentation

#44 Feat: add web terminal
  docs/en/getting-started/quick-start.md
  docs/zh/getting-started/quick-start.md
  infra/kdp-core/resources/kdp-cloudtty.cue
  infra/kdp-core/resources/kdp-oam-operator.cue
  infra/kdp-core/template.cue
Labels: enhancement

#71 Feat: add airbyte app
  catalog/airbyte/README.md
  catalog/airbyte/apps/airbyte.app/README.md
  catalog/airbyte/apps/airbyte.app/app.yaml
  catalog/airbyte/apps/airbyte.app/i18n/en/README.md
  catalog/airbyte/apps/airbyte.app/metadata.yaml
  catalog/airbyte/i18n/en/README.md
  catalog/airbyte/metadata.yaml
  catalog/airbyte/x-definitions/app-airbyte.cue
Labels: enhancement

#69 Feat: add superset app
  catalog/superset/README.md
  catalog/superset/apps/superset.app/README.md
  catalog/superset/apps/superset.app/app.yaml
  catalog/superset/apps/superset.app/i18n/en/README.md
  catalog/superset/apps/superset.app/metadata.yaml
  catalog/superset/i18n/en/README.md
  catalog/superset/metadata.yaml
  catalog/superset/x-definitions/app-superset.cue
Labels: enhancement

#76 Docs: Exploring data using airbyte, clickhouse, and superset
  docs/en/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/images/airbyte01.png
  docs/images/airbyte02.png
  docs/images/airbyte03.png
  docs/images/airbyte04.png
  docs/images/superset01.png
  docs/images/superset02.png
  docs/images/superset03.png
  docs/zh/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
Labels: documentation

#79 Fix: update mysql parameters auth.password and fix regex
  catalog/mysql/apps/mysql.app/app.yaml
  catalog/mysql/x-definitions/app-mysql.cue
  catalog/superset/apps/superset.app/README.md
  catalog/superset/apps/superset.app/i18n/en/README.md
Labels: bug

#82 Fix: delete loki grafana operator
  infra/plg-stack/resources/loki.cue
Labels: bug

#83 Feat: add description of flags to spark-distcp tutorials
  docs/en/user-tutorials/import-from-hdfs-to-hdfs.md
  docs/zh/user-tutorials/import-from-hdfs-to-hdfs.md
Labels: documentation

#84 Fix: add missing env parameters for airbyte
  catalog/airbyte/x-definitions/app-airbyte.cue
Labels: bug

#87 Fix: update mysql innodb_buffer_pool_size to reasonable range (#85)
  catalog/mysql/apps/mysql.app/app.yaml
Labels: cherry pick

#86 Fix: incorrect default DS url of Grafana
  infra/plg-stack/resources/prometheus.cue
Labels: bug

#88 Fix: fix clickhouse parameters and dashboard
  catalog/clickhouse/x-definitions/app-clickhouse.cue
Labels: bug

#91 Fix: fix clickhouse parameters and dashboard
  catalog/clickhouse/x-definitions/app-clickhouse.cue
Labels: cherry pick

#89 Chore: update superset airbyte apps image registry
  catalog/airbyte/x-definitions/app-airbyte.cue
  catalog/superset/x-definitions/app-superset.cue
Labels: enhancement

#90 Chore: update superset airbyte apps image registry
  catalog/airbyte/x-definitions/app-airbyte.cue
  catalog/superset/x-definitions/app-superset.cue
Labels: enhancement, cherry pick

#92 Chore: change the folder path of tutorial images
  docs/en/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/en/user-tutorials/images/airbyte01.png
  docs/en/user-tutorials/images/airbyte02.png
  docs/en/user-tutorials/images/airbyte03.png
  docs/en/user-tutorials/images/airbyte04.png
  docs/en/user-tutorials/images/superset01.png
  docs/en/user-tutorials/images/superset02.png
  docs/en/user-tutorials/images/superset03.png
  docs/zh/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/zh/user-tutorials/images/airbyte01.png
  docs/zh/user-tutorials/images/airbyte02.png
  docs/zh/user-tutorials/images/airbyte03.png
  docs/zh/user-tutorials/images/airbyte04.png
  docs/zh/user-tutorials/images/superset01.png
  docs/zh/user-tutorials/images/superset02.png
  docs/zh/user-tutorials/images/superset03.png
Labels: documentation

#95 Chore: change the folder path of tutorial images
  docs/en/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/en/user-tutorials/images/airbyte01.png
  docs/en/user-tutorials/images/airbyte02.png
  docs/en/user-tutorials/images/airbyte03.png
  docs/en/user-tutorials/images/airbyte04.png
  docs/en/user-tutorials/images/superset01.png
  docs/en/user-tutorials/images/superset02.png
  docs/en/user-tutorials/images/superset03.png
  docs/zh/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/zh/user-tutorials/images/airbyte01.png
  docs/zh/user-tutorials/images/airbyte02.png
  docs/zh/user-tutorials/images/airbyte03.png
  docs/zh/user-tutorials/images/airbyte04.png
  docs/zh/user-tutorials/images/superset01.png
  docs/zh/user-tutorials/images/superset02.png
  docs/zh/user-tutorials/images/superset03.png
Labels: enhancement, cherry pick

#94 Feat: add a startup probe for StreamPark in case it takes a long time…
  catalog/flink/x-definitions/app-streampark.cue
Labels: enhancement, cherry pick

#99 Fix: Control The mysql mode cannot be changed after installation
  catalog/mysql/apps/mysql.app/app.yaml
  catalog/mysql/x-definitions/app-mysql.cue
Labels: enhancement

#104 Chore: format airflow cue def
  catalog/airflow/x-definitions/app-airflow.cue
Labels: cherry pick

#102 Docs: Add tutorials of KDP installation on main stream Kubernetes management platforms
  docs/en/user-tutorials/images/kdp-ux-landing-page.png
  docs/en/user-tutorials/images/ks-cluster-overview.png
  docs/en/user-tutorials/images/ks-kdp-install.png
  docs/en/user-tutorials/images/ks-kdp-ux-access-service.png
  docs/en/user-tutorials/images/ks-kdp-ux-ingress.png
  docs/en/user-tutorials/images/ks-monitoring.png
  docs/en/user-tutorials/images/ks-web-kubectl.png
  docs/en/user-tutorials/images/rancher-arch.png
  docs/en/user-tutorials/images/rancher-ds-cluster-monitoring.png
  docs/en/user-tutorials/images/rancher-ds-cluster.png
  docs/en/user-tutorials/images/rancher-k8s-dist.png
  docs/en/user-tutorials/images/rancher-kdp-install-ok.png
  docs/en/user-tutorials/images/rancher-kdp-ux-ingress.png
  docs/en/user-tutorials/images/rancher-kubectl-shell.png
  docs/en/user-tutorials/images/rancher-overview.png
  docs/en/user-tutorials/install-kdp-on-kubesphere-101.md
  docs/en/user-tutorials/install-kdp-on-rancher-101.md
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/images/kdp-ux-landing-page.png
  docs/zh/user-tutorials/images/ks-cluster-overview.png
  docs/zh/user-tutorials/images/ks-kdp-install.png
  docs/zh/user-tutorials/images/ks-kdp-ux-access-service.png
  docs/zh/user-tutorials/images/ks-kdp-ux-ingress.png
  docs/zh/user-tutorials/images/ks-monitoring.png
  docs/zh/user-tutorials/images/ks-web-kubectl.png
  docs/zh/user-tutorials/images/rancher-arch.png
  docs/zh/user-tutorials/images/rancher-ds-cluster-monitoring.png
  docs/zh/user-tutorials/images/rancher-ds-cluster.png
  docs/zh/user-tutorials/images/rancher-k8s-dist.png
  docs/zh/user-tutorials/images/rancher-kdp-install-ok.png
  docs/zh/user-tutorials/images/rancher-kdp-ux-ingress.png
  docs/zh/user-tutorials/images/rancher-kubectl-shell.png
  docs/zh/user-tutorials/images/rancher-overview.png
  docs/zh/user-tutorials/install-kdp-on-kubesphere-101.md
  docs/zh/user-tutorials/install-kdp-on-rancher-101.md
  docs/zh/user-tutorials/tutorials.md
Labels: documentation

#105 Fix: mysql arch should not be able to change after installation (#99)
  catalog/mysql/apps/mysql.app/app.yaml
  catalog/mysql/x-definitions/app-mysql.cue
Labels: cherry pick

#108 Fix: handling the issue of context lifecycle being inconsistent with …
  catalog/mysql/apps/mysql.app/app.yaml
  catalog/mysql/x-definitions/app-mysql.cue
Labels: cherry pick

#110 Fix: remove ingress trait parameter ingressClassName, use k8s default class
  catalog/flink/x-definitions/app-streampark.cue
  catalog/hue/x-definitions/app-hue.cue
  infra/kdp-core/definitions/trait-bdos-ingress.cue
  infra/kong/template.cue
Labels: bug

#109 Feat(airflow): use kubernetes_executor as airflow default executor, use git sync dags and add tutorials
  catalog/airflow/apps/airflow.app/README.md
  catalog/airflow/apps/airflow.app/app.yaml
  catalog/airflow/apps/airflow.app/i18n/en/README.md
  catalog/airflow/x-definitions/app-airflow.cue
  docs/en/user-tutorials/batch-job-scheduling-for-hive-sql-with-apache-airflow.md
  docs/en/user-tutorials/images/airflow01.png
  docs/en/user-tutorials/images/airflow02.png
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/batch-job-scheduling-for-hive-sql-with-apache-airflow.md
  docs/zh/user-tutorials/images/airflow01.png
  docs/zh/user-tutorials/images/airflow02.png
  docs/zh/user-tutorials/tutorials.md
Labels: documentation, enhancement

#113 Feat(airflow): use kubernetes_executor as airflow default executor, use git sync dags and add tutorials
  catalog/airflow/apps/airflow.app/README.md
  catalog/airflow/apps/airflow.app/app.yaml
  catalog/airflow/apps/airflow.app/i18n/en/README.md
  catalog/airflow/x-definitions/app-airflow.cue
  docs/en/user-tutorials/batch-job-scheduling-for-hive-sql-with-apache-airflow.md
  docs/en/user-tutorials/images/airflow01.png
  docs/en/user-tutorials/images/airflow02.png
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/batch-job-scheduling-for-hive-sql-with-apache-airflow.md
  docs/zh/user-tutorials/images/airflow01.png
  docs/zh/user-tutorials/images/airflow02.png
  docs/zh/user-tutorials/tutorials.md
Labels: cherry pick

#111 Fix(ingress): remove ingress trait parameter ingressClassName, use k8s default class
  catalog/flink/x-definitions/app-streampark.cue
  catalog/hue/x-definitions/app-hue.cue
  infra/kdp-core/definitions/trait-bdos-ingress.cue
  infra/kong/template.cue
Labels: cherry pick
