Repository linktimecloud/kubernetes-data-platform, pull requests merged in 2024-07, with the labels that each got.

#141 Feat(hue): Add a switch to enable/disable HDFS file browsing
  catalog/hue/x-definitions/app-hue.cue
Labels: enhancement

#145 Feat: Add Iceberg Support
  catalog/flink/apps/flink-session-cluster.app/app.yaml
  catalog/flink/x-definitions/app-flink.cue
  catalog/hive/apps/hive-metastore.app/app.yaml
  catalog/hive/apps/hive-server2.app/app.yaml
  catalog/hive/x-definitions/app-hive-metastore.cue
  catalog/hive/x-definitions/app-hive-server2.cue
  catalog/spark/apps/spark-history-server.app/app.yaml
  docs/en/user-tutorials/iceberg-quickstart.md
  docs/en/user-tutorials/images/iceberg-quickstart-metadata.png
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/iceberg-quickstart.md
  docs/zh/user-tutorials/images/iceberg-quickstart-metadata.png
  docs/zh/user-tutorials/tutorials.md
Labels: documentation, feature

#142 Feat: Add milvus
  catalog/milvus/README.md
  catalog/milvus/apps/milvus.app/README.md
  catalog/milvus/apps/milvus.app/app.yaml
  catalog/milvus/apps/milvus.app/i18n/en/README.md
  catalog/milvus/apps/milvus.app/metadata.yaml
  catalog/milvus/i18n/en/README.md
  catalog/milvus/metadata.yaml
  catalog/milvus/x-definitions/app-milvus.cue
Labels: documentation, enhancement

#146 Fix: Adapt to multiple Ingress Classes
  infra/kdp-core/resources/kdp-cloudtty.cue
  infra/kdp-core/resources/kdp-ingress-middleware.cue
  infra/kdp-core/template.cue
Labels: enhancement

#147 Fix: update cloudtty ingress object works with different ingress cont…
  infra/kdp-core/resources/kdp-cloudtty.cue
  infra/kdp-core/resources/kdp-ingress-middleware.cue
  infra/kdp-core/template.cue
Labels: cherry pick

#148 Docs: fix juicefs docs
  catalog/juicefs/apps/juicefs-s3-gateway.app/README.md
  catalog/juicefs/apps/juicefs-s3-gateway.app/i18n/en/README.md
  catalog/juicefs/x-definitions/app-juicefs-s3-gateway.cue
Labels: bug

#150 Fix: deal with the web terminal entry is restored to the original state
  infra/kdp-core/template.cue
Labels: bug, title-needs-formatting

#155 Fix: deal with the web terminal entry is restored to the original state (#150)
  infra/kdp-core/template.cue
Labels: cherry pick

#135 Docs: Add KDP offline install docs
  docs/zh/getting-started/images/fluxcd-update.png
  docs/zh/getting-started/images/nexus-docker-proxy.png
  docs/zh/getting-started/images/nexus-raw.png
  docs/zh/getting-started/images/nexus-realms.png
  docs/zh/getting-started/offline-install.md
Labels: documentation, enhancement

#161 Fix: fix metadata of iceberg related images
  catalog/clickhouse/apps/clickhouse.app/app.yaml
  catalog/flink/apps/flink-session-cluster.app/metadata.yaml
  catalog/hive/apps/hive-metastore.app/metadata.yaml
  catalog/hive/apps/hive-server2.app/metadata.yaml
  catalog/spark/apps/spark-history-server.app/metadata.yaml
Labels: bug

#166 Fix: deal with job container creating
  infra/kdp-core/resources/kdp-cloudtty.cue
Labels: bug

#149 Feat: add Ollama app
  catalog/airflow/app-flink.cue
  catalog/ollama/README.md
  catalog/ollama/apps/ollama.app/README.md
  catalog/ollama/apps/ollama.app/app.yaml
  catalog/ollama/apps/ollama.app/i18n/en/README.md
  catalog/ollama/apps/ollama.app/metadata.yaml
  catalog/ollama/i18n/en/README.md
  catalog/ollama/metadata.yaml
  catalog/ollama/x-definitions/app-ollama.cue
Labels: feature

#171 Feat: add elasticsearch app
  catalog/elasticsearch/README.md
  catalog/elasticsearch/apps/elasticsearch.app/README.md
  catalog/elasticsearch/apps/elasticsearch.app/app.yaml
  catalog/elasticsearch/apps/elasticsearch.app/i18n/en/README.md
  catalog/elasticsearch/apps/elasticsearch.app/metadata.yaml
  catalog/elasticsearch/i18n/en/README.md
  catalog/elasticsearch/metadata.yaml
  catalog/elasticsearch/x-definitions/app-elasticsearch.cue
  catalog/elasticsearch/x-definitions/setting-elasticsearch.cue
Labels: feature

#170 Feat: Add llm rag guide
  docs/en/user-tutorials/images/llm-rag-01.jpg
  docs/en/user-tutorials/llm-rag-guide.md
  docs/en/user-tutorials/tutorials.md
  docs/zh/user-tutorials/images/llm-rag-01.jpg
  docs/zh/user-tutorials/llm-rag-guide.md
  docs/zh/user-tutorials/tutorials.md
Labels: documentation

#176 Feat: Hive supports dynamic configuration of authentication modes #175
  catalog/hive/apps/hive-server2.app/app.yaml
  catalog/hive/x-definitions/app-hive-server2.cue
  catalog/hue/x-definitions/app-hue.cue
Labels: enhancement
