Repository linktimecloud/kubernetes-data-platform, pull requests merged in 2024-06, with the labels that each got.

#121 Fix: deal with resource ownerReferences
  infra/kdp-core/template.cue
Labels: bug

#120 Fix: Remove the httpfs context setting when uninstalling the httpfs app
  catalog/hdfs/x-definitions/app-httpfs.cue
Labels: bug

#119 Fix: delete nil for architecture list
  catalog/mysql/x-definitions/app-mysql.cue
Labels: bug, cherry pick

#118 Fix: delete nil for architecture list
  catalog/mysql/x-definitions/app-mysql.cue
Labels: bug

#122 Fix: deal with resource ownerReferences (#121)
  infra/kdp-core/template.cue
Labels: bug, cherry pick

#123 Fix: Remove context setting when uninstalling the httpfs app (#120)
  catalog/hdfs/x-definitions/app-httpfs.cue
Labels: cherry pick

#124 Fix: update kdp version
  infra/kdp-core/template.cue
Labels: bug

#126 Fix: update kdp cmd version
  cmd/const.go
Labels: bug

#130 Docs: Visualization Analysis of Taobao Maternal and Infant Shopping Data
  catalog/superset/x-definitions/app-superset.cue
  docs/en/user-tutorials/images/airbyte05.png
  docs/en/user-tutorials/images/airbyte06.png
  docs/en/user-tutorials/visualization-analysis-of-taobao's-maternal-and-infant-shopping-data.md
  docs/zh/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md
  docs/zh/user-tutorials/images/airbyte05.png
  docs/zh/user-tutorials/images/airbyte06.png
  docs/zh/user-tutorials/images/airflow03.png
  docs/zh/user-tutorials/images/airflow04.png
  docs/zh/user-tutorials/images/airflow05.png
  docs/zh/user-tutorials/images/kdp01.png
  docs/zh/user-tutorials/images/superset04.png
  docs/zh/user-tutorials/images/superset05.png
  docs/zh/user-tutorials/images/superset06.png
  docs/zh/user-tutorials/images/superset07.png
  docs/zh/user-tutorials/images/superset08.png
  docs/zh/user-tutorials/visualization-analysis-of-taobao's-maternal-and-infant-shopping-data.md
Labels: documentation, cherry pick

#131 Docs: Add real time increment data analysis docs
  docs/en/user-tutorials/Real-time-incremental-data-analysis.md
  docs/en/user-tutorials/images/Real-time-incremental-data-analysis-workflow.jpg
  docs/en/user-tutorials/images/superset-Real-time-incremental-data-analysis-01.png
  docs/zh/user-tutorials/Real-time-incremental-data-analysis.md
  docs/zh/user-tutorials/images/Real-time-incremental-data-analysis-workflow.jpg
  docs/zh/user-tutorials/images/superset-Real-time-incremental-data-analysis-01.png
Labels: documentation

#134 Docs: Add real time increment data analysis docs (#131)
  docs/en/user-tutorials/Real-time-incremental-data-analysis.md
  docs/en/user-tutorials/images/Real-time-incremental-data-analysis-workflow.jpg
  docs/en/user-tutorials/images/superset-Real-time-incremental-data-analysis-01.png
  docs/zh/user-tutorials/Real-time-incremental-data-analysis.md
  docs/zh/user-tutorials/images/Real-time-incremental-data-analysis-workflow.jpg
  docs/zh/user-tutorials/images/superset-Real-time-incremental-data-analysis-01.png
Labels: documentation, cherry pick

#138 Feat: add ttlSecondsAfterFinished for hms job
  catalog/hive/x-definitions/app-hive-metastore.cue
Labels: cherry pick
